#!/bin/bash
# Distro Hopper's Friend
# David F Muller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Version 0.3.2-alpha

if [ $EUID -ne 0 ]
then
   	echo "This script must be run as with root privilege (NOT AS ROOT), type: sudo ./Distro_Hoppers_Friend" 
   	exit 1
else
	echo "Welcome to the Distro Hopper's Friend"
    echo "If you have any doubts about me or this script, please review the code before running"
    echo "(You really should do this anyway! ;-) )"
    echo
    echo "OK then, let's get started!"

    #Gather Basic Info
    	echo "What is your user name?: "
	    read -r USENAM
        if [ "$USENAM" != "$USER" ]; then
            echo "There was a mismatch in usernames that will cause issues...script will now exit"
            exit 1
        fi
        USENAM=${USENAM,,}

    #Auto Entry of Sudo Password in the Terminal
    	echo "Do you want to auto enter your sudo password when in a terminal? (Y/n): "
	    read -r PASSWD
        PASSWD=${PASSWD^}

    #Dedicated Data/Home Partition
        echo "Do you have a seperate/dedicated data partition that holds your Home folders? (Y/n): "
	    read -r SEPDATA
        SEPDATA=${SEPDATA^}

    #Determine Base Distro
        echo "What Distro is your current install based on? (i.e. Ubuntu, Fedora)"
        echo "(U-ubuntu, A-arch, C-arcolinux, D-debian, F-fedora, O-opensuse)?: "
	    read -r DISTBASE
        DISTBASE=${DISTBASE^}
        if [ -z "$DISTBASE" ]; then
            echo "I will assume Ubuntu"
            DISTBASE='U';
        elif [ "$DISTBASE" == 'O' ];
            then
                echo "Is your distro based on L-leap or T-tumbleweed?"
                read -r SUSESUB
                SUSESUB=${SUSESUB^}
                if [ "$SUSESUB" != 'T'];
                    then
                    echo "Assuming Leap as the base."
                    SUSESUB='L'
                fi
        elif [ "$DISTBASE" == 'F' ];
            then
                echo "Which version # of Fedora? (i.e. 27 or 28)"
                read -r FEDSUB
        fi
    
    #Additional PPAs and/or Repositories
        echo "Would you like to install additional PPAs/Repositories (Currently only for Ubuntu, Debian, and Fedora)? (Y/n): "
	    read -r ADDREPO
        ADDREPO=${ADDREPO^}

    #Snaps and Flatpaks
        echo "Would you like to enable Snaps and Flatpaks?"
        echo "These are required for some of the Additional Software Installs (Y/n): "
	    read -r SNAPFLAT
        SNAPFLAT=${SNAPFLAT^}

    #Additional Software
        echo "Would you like to install additional software (Currently only for Ubuntu)? (Y/n): "
	    read -r ADDAPPS
        ADDAPPS=${ADDAPPS^}

    #End of Gathering Info

    #Start of Actual Work
        echo "OK then, thats all I need for now, lets get started!"

	#Updating Sudoers File to Add NOPASSWD to User
        if [[ "$PASSWD" == 'Y' || -z "$PASSWD" ]];
        then
            echo "Adding NOPASSWD to sudoers file"
	    	echo "$USENAM ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
        else
            echo "$USENAM ALL=(ALL:ALL) ALL" | sudo tee -a /etc/sudoers
        fi
	
	#Seperate Home/Data Partition

        if [[ "$SEPDATA" == 'Y' || -z "$SEPDATA" ]];
        then
            #Core Operations
                PERMHOME=/home/$USENAM/.home
                echo "What is the absolute path (i.e. /dev/sda1) of your data/home partition?: "
 	            read -r PERMDATA
                PERMDATA=${PERMDATA,,}
                echo "What is the filesystem (i.e. ext4) of your data/home partition?: "
		        read -r UPDATEFSTAB
                PERMUUID=$( blkid -s UUID -o value "$PERMDATA" )
                sudo echo "UUID=$PERMUUID $PERMHOME $UPDATEFSTAB users,exec,rw,auto,noatime 0 2" | sudo tee -a /etc/fstab
    
            #Setup Directories for Mounting
        		echo "Creating directory for mounting"
		        mkdir $PERMHOME
			
        	#Setup home folder
        		echo "Mounting, setting up, and linking home folder"
            	echo "These folders are based on what I have, YMMV, you will need to manually remove/link"
            	echo "any folders you use that I do not"
	    		sudo mount $PERMDATA $PERMHOME
			
    		#Remove original folders and set symbolic links
    			if [ -d "$PERMHOME/Documents" ]
                then
                    if [ -d "/home/$USENAM/Documents" ]; then sudo rm -Rf "/home/$USENAM/Documents"; fi
                    sudo ln -s "$PERMHOME/Documents" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Downloads" ]
                then
                    if [ -d "/home/$USENAM/Downloads" ]; then sudo rm -Rf "/home/$USENAM/Downloads"; fi
                    sudo ln -s "$PERMHOME/Downloads" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Etcher" ]
                then
                    if [ -d "/home/$USENAM/Etcher" ]; then sudo rm -Rf "/home/$USENAM/Etcher"; fi
                    sudo ln -s "$PERMHOME/Etcher" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Games" ]
                then
                    if [ -d "/home/$USENAM/Games" ]; then sudo rm -Rf "/home/$USENAM/Games"; fi
                    sudo ln -s "$PERMHOME/Games" "/home/$USENAM"
                fi
                if [ -d "$PERMHOME/Github" ]
                then
                    if [ -d "/home/$USENAM/Github" ]; then sudo rm -Rf "/home/$USENAM/Github"; fi
                    sudo ln -s "$PERMHOME/Github" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Google_Drive" ]
                then
                    if [ -d "/home/$USENAM/Google_Drive" ]; then sudo rm -Rf "/home/$USENAM/Google_Drive"; fi
                    sudo ln -s "$PERMHOME/Google_Drive" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Links" ]
                then
                    if [ -d "/home/$USENAM/Links" ]; then sudo rm -Rf "/home/$USENAM/Links"; fi
                    sudo ln -s "$PERMHOME/Links" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Music" ]
                then
                    if [ -d "/home/$USENAM/Music" ]; then sudo rm -Rf "/home/$USENAM/Music"; fi
                    sudo ln -s "$PERMHOME/Music" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Pictures" ]
                then
                    if [ -d "/home/$USENAM/Pictures" ]; then sudo rm -Rf "/home/$USENAM/Pictures"; fi
                    sudo ln -s "$PERMHOME/Pictures" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Scripts" ]
                then
                    if [ -d "/home/$USENAM/Scripts" ]; then sudo rm -Rf "/home/$USENAM/Scripts"; fi
                    sudo ln -s "$PERMHOME/Scripts" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Softmaker" ]
                then
                    if [ -d "/home/$USENAM/Softmaker" ]; then sudo rm -Rf "/home/$USENAM/Softmaker"; fi
                    sudo ln -s "$PERMHOME/Softmaker" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Videos" ]
                then
                    if [ -d "/home/$USENAM/Videos" ]; then sudo rm -Rf "/home/$USENAM/Videos"; fi
                    sudo ln -s "$PERMHOME/Videos" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/VPNac" ]
                then
                    if [ -d "/home/$USENAM/VPNac" ]; then sudo rm -Rf "/home/$USENAM/VPNac"; fi
                    sudo ln -s "$PERMHOME/VPNac" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Wallpapers" ]
                then
                    if [ -d "/home/$USENAM/Wallpapers" ]; then sudo rm -Rf "/home/$USENAM/Wallpapers"; fi
                    sudo ln -s "$PERMHOME/Wallpapers" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/Working" ]
                then
                    if [ -d "/home/$USENAM/Working" ]; then sudo rm -Rf "/home/$USENAM/Working"; fi
                    sudo ln -s "$PERMHOME/Working" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/.gnupg" ]
                then
                    if [ -d "/home/$USENAM/.gnupg" ]; then sudo rm -Rf "/home/$USENAM/.gnupg"; fi
                    sudo ln -s "$PERMHOME/.gnupg" "/home/$USENAM"
                fi
                if [ -d "$PERMHOME/.gdfuse" ]
                then
                    if [ -d "/home/$USENAM/.gdfuse" ]; then sudo rm -Rf "/home/$USENAM/.gdfuse"; fi
                    sudo ln -s "$PERMHOME/.gdfuse" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/.mozilla" ]
                then
                    if [ -d "/home/$USENAM/.mozilla" ]; then sudo rm -Rf "/home/$USENAM/.mozilla"; fi
                    sudo ln -s "$PERMHOME/.mozilla" "/home/$USENAM"
                fi
                if [ -d "$PERMHOME/.ssh" ]
                then
                    if [ -d "/home/$USENAM/.ssh" ]; then sudo rm -Rf "/home/$USENAM/.ssh"; fi
                    sudo ln -s "$PERMHOME/.ssh" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/.steam" ]
                then
                    if [ -d "/home/$USENAM/.steam" ]; then sudo rm -Rf "/home/$USENAM/.steam"; fi
                    sudo ln -s "$PERMHOME/.steam" "/home/$USENAM"
                fi
	    		if [ -d "$PERMHOME/.thunderbird" ]
                then
                    if [ -d "/home/$USENAM/.thunderbird" ]; then sudo rm -Rf "/home/$USENAM/.thunderbird"; fi
                    sudo ln -s "$PERMHOME/.thunderbird" "/home/$USENAM"
                fi
                if [ -d "$PERMHOME/.vscode" ]
                then
                    if [ -d "/home/$USENAM/.vscode" ]; then sudo rm -Rf "/home/$USENAM/.vscode"; fi
                    sudo ln -s "$PERMHOME/.vscode" "/home/$USENAM"
                fi
                if [ -d "$PERMHOME/.zoom" ]
                then
                    if [ -d "/home/$USENAM/.zoom" ]; then sudo rm -Rf "/home/$USENAM/.zoom"; fi
                    sudo ln -s "$PERMHOME/.zoom" "/home/$USENAM"
                fi
                if [ -f "$PERMHOME/.pam-gnupg" ]
                then
                    if [ -f "/home/$USENAM/.pam-gnupg" ]; then sudo rm -f "/home/$USENAM/.pam-gnupg"; fi
                    sudo ln -s "$PERMHOME/.pam-gnupg" "/home/$USENAM"
                fi
            #Setting up my personal desktop extra directories and hosts file
                if [[ "$USENAM" == 'david' && "$HOSTNAME" == 'Dragon01' ]];
                then
                    echo "Fetching needed files"
                    wget  https://github.com/Dreamingwolf/Setup-Scripts/raw/master/Dragon01_hosts
                    echo "Creating directories for mounting"
                    sudo mkdir /StorageBunker
                    sudo mkdir /Backup
                    #Core Operations
                        HOMEPART=/home/david/.home
                        HOMEDATA=/dev/nvme0n1p1
                        HOMEFSTAB=$( blkid -s TYPE -o value "$HOMEDATA" )
                        HOMEUUID=$( blkid -s UUID -o value "$HOMEDATA" )
                        
                        BACKUPDATA=$( blkid -L Backup )
                        BACKUPFSTAB=$( blkid -s TYPE -o value "$BACKUPDATA" )
                        BACKUPUUID=$( blkid -s UUID -o value "$BACKUPDATA" )

                        STORAGEDATA=$( blkid -L StorageBunker )
                        STORAGEFSTAB=$( blkid -s TYPE -o value "$STORAGEDATA" )
                        STORAGEUUID=$( blkid -s UUID -o value "$STORAGEDATA" )

                    #Updating /etc/fstab
                        echo "Adding disks to /etc/fstab"
                        echo "UUID=$HOMEUUID $HOMEPART $HOMEFSTAB users,exec,rw,auto,noatime 0 2
                        UUID=$BACKUPUUID /Backup $BACKUPFSTAB users,exec,rw,auto,noatime,uid=$( id -u david ),gid=$( id -g david ) 0 2
                        UUID=$STORAGEUUID /StorageBunker $STORAGEFSTAB users,exec,rw,auto,noatime,uid=$( id -u david ),gid=$( id -g david ) 0 2" | sudo tee -a /etc/fstab

                    echo "Updating the hosts file"
                    sudo mv -f ./Dragon01_hosts /etc/hosts
                    echo "Cleaning up"
                    sudo rm ./Dragon01_hosts
                 fi
            #Assuring ownership of the new links
                sudo chown -R $USENAM:$USENAM /home/$USENAM
        fi

	#Setting up additional PPAs and other Repositories
        if [[ "$ADDREPO" == 'Y' || -z "$ADDREPO" ]];
        then
            case $DISTBASE in
                U)
                    #Base Repos
                        sudo apt-add-repository -yn main
                        sudo apt-add-repository -yn restricted
                        sudo apt-add-repository -yn universe
                        sudo apt-add-repository -yn multiverse
                        sudo apt install -y curl

                    #PPAs

                        # Warning
                            echo "Adding additional PPAs"
                            echo "BE WARNED - Not all PPAs have release pages for all versions of Ubuntu. Be sure to verify and correct any issues after installation!"

                        # PPA Installation Commands

                            sudo apt install dialog
                            cmd1=(dialog --separate-output --checklist "Please Select PPAs you want to install:" 22 76 16)
                            options1=(1 "Canonical Kernal Team" off    # any option can be set to default to "on"
                                2 "Daniel Richter - grub-customizer" off 
                                3 "Etcher" off
                                4 "Nvidia Drivers" off
                                5 "Linux Uprising - Oracle Java 10" off
                                6 "Lutris" off
                                7 "LXQT Team" off
                                8 "LXQT Team - Testing" off
                                9 "Firefox-Nightly" off
                                10 "Thunderbird Beta" off
                                11 "OBS Project" off
                                12 "Otto Kesselgulasch - Gimp" off
                                13 "Peppermint 9" off
                                14 "Steam" off
                                15 "Tony George - Timeshift etc" off
                                16 "Virtualbox" off
                                17 "Visual Studio Code" off
                                18 "WebUpd8 Team" off
                                19 "XFCE - xubuntu-dev-extra" off
                                20 "XFCE - xubuntu-dev-experimental" off
                                21 "KDE - kubuntu backports" off
                                22 "Oibaf - open video drivers for radeon, intel and nvidia" off
                                23 "Sarnex - Wine + Gallium Nine" off
                                24 "Maarten Baert - simplescreenrecorder" off
                                25 "RVM - smplayer gtk" off
                                26 "RVM - smplayer qt4" off
                                27 "Sublime Text" off)
                        #The Rest are here merely to allow for easy expansion
                            #			 28 "" off
                            #			 29 "" off
                            #			 30 "" off

                            choices1=$("${cmd1[@]}" "${options1[@]}" 2>&1 >/dev/tty)
                            clear
                            for choice1 in $choices1;
                            do                   
                                case $choice1 in
                            
                                    1)
                                        #Canonical Kernal Team
                                        echo "Installing Canonical Kernal Team PPA"
                                        sudo add-apt-repository -yn ppa:canonical-kernal-team/ppa
                                        ;;

                                    2)
                                        #Daniel Richter
                                        echo "Installing Daniel Richter's PPA for grub-customizer"
                                        sudo add-apt-repository -yn ppa:danielrichter2007/grub-customizer
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/danielrichter2007*; fi
                                        ;;

                                    3)	
                                        #Etcher
                                        echo "Installing Etcher Repository"
                                        echo "deb https://dl.bintray.com/resin-io/debian stable etcher" | sudo tee /etc/apt/sources.list.d/etcher.list
                                        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
                                        ;;
                                
                                    4)
                                        #Nvidia Drivers
                                        echo "Installing Graphics Drivers PPA for Nvidia drivers"
                                        sudo add-apt-repository -yn ppa:graphics-drivers/ppa
                                        ;;

                                    5)
                                        #Linux Uprising Java 10
                                        echo "Installing Linux Uprising PPA for Oracle Java 10"
                                        sudo add-apt-repository -yn ppa:linuxuprising/java
                                        ;;

                                    6)
                                        #Lutris
                                        echo "Installing Lutris Repository"
                                        ver=$(lsb_release -sr);
                                        if [ "$ver" != "18.04" ] && [ "$ver" != "17.10" ] && [ "$ver" != "17.04" ] && [ "$ver" != "16.04" ]; then ver="18.04"; fi
                                        echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                                        wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_"$ver"/Release.key -O- | sudo apt-key add -
                                        ;;

                                    7)
                                        #LXQT Team
                                        echo "Installing LXQT Team PPA"
                                        sudo add-apt-repository -yn ppa:lxqt/ppa
                                        ;;

                                    8)
                                        #LXQT Team - Testing
                                        echo "Installing LXQT Team - Testing PPA"
                                        sudo add-apt-repository -yn ppa:lxqt/testing
                                        ;;

                                    9)
                                        #Firefox-Nightly
                                        echo "Installing PPA for Firefox Nightly. Install as firefox-trunk."
                                        sudo add-apt-repository -yn ppa:ubuntu-mozilla-daily/ppa
                                        ;;

                                    10)
                                        #Thunderbird Beat
                                        echo "Installing PPA for Thunderbird Beta. Install as thunderbird."
                                        sudo add-apt-repository -yn ppa:mozillateam/thunderbird-next
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/mozillateam*; fi
                                        ;;

                                    11)
                                        #OBS Project
                                        echo "Installing OBSProject PPA"
                                        sudo add-apt-repository -yn ppa:obsproject/obs-studio
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/obsproject*; fi
                                        ;;

                                    12)
                                        #Otto Kesselgulasch
                                        #Need to expand later for multiple choice within Otto's repos
                                        echo "Installing Otto Kesselgulasch PPA for Gimp"
                                        sudo add-apt-repository -yn ppa:otto-kesselgulasch/gimp
                                        ;;

                                    13)
                                        #Peppermint 9
                                        echo "Installing Release PPA for Peppermint 9 OS"
                                        sudo add-apt-repository -yn ppa:peppermintos/p9-release
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/peppermint*; fi
                                        ;;

                                    14)
                                        #Steam
                                        echo "Installing Steam PPA for Ubuntu Precise"
                                        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B05498B7
                                        sudo sh -c 'echo "deb http://repo.steampowered.com/steam/ precise steam" | sudo tee -a /etc/apt/sources.list.d/steam.list'
                                        ;;

                                    15)
                                        #Tony George
                                        echo "Installing Tony George PPA for timeshift, etc"
                                        sudo add-apt-repository -yn ppa:teejee2008/ppa
                                        ;;

                                    16)
                                        #Virtualbox
                                        echo "Installing Virtualbox Repository"
                                        wget -q -O - https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
                                        wget -q -O - https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
                                        sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list'
					                    if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/virtualbox*; fi
                                        ;;

                                    17)
                                        #Visual Studio Code
                                        echo "Installing Visual Studio Code Repository. Install as code"
                                        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
                                        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
                                        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
                                        ;;

                                    18)
                                        #WebUpd8 Team
                                        #Need to expand later for multiple choice within WebUpd8's repos
                                        echo "Installing WebUpd8 PPA for PPA Manager"
                                        sudo add-apt-repository -yn ppa:webupd8team/y-ppa-manager
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/webupd8team*; fi
                                        ;;
                                        
                                    19)
                                        #XFCE - xubuntu-dev-extra
                                        echo "Installing xubuntu-dev-extras for XFCE"
                                        sudo add-apt-repository -yn ppa:xubuntu-dev/extras
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/xubuntu-dev-ubuntu-extras*; fi
                                        ;;

                                    20)
                                        #XFCE - xubuntu-dev-experimental
                                        echo "Installing xubuntu-dev-experimental for XFCE"				
                                        sudo add-apt-repository -yn ppa:xubuntu-dev/experimental
                                        ;;

                                    21)
                                        #KDE kubuntu backports
                                        echo "Installing kubuntu backports PPA for KDE"
                                        sudo add-apt-repository -yn ppa:kubuntu-ppa/backports
                                        ;;

                                    22)
                                        #Oibaf - open video drivers
                                        sudo add-apt-repository -yn ppa:oibaf/graphics-drivers
                                        ;;
                    
                                    23)
                                        #Sarnex - Wine + Gallium Nine
                                        sudo add-apt-repository -yn ppa:commendsarnex/winedri3
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/commendsarnex*; fi
                                        ;;

                                    24)
                                        #Maarten Baert - simplescreenrecorder
                                        sudo add-apt-repository -yn ppa:maarten-baert/simplescreenrecorder
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/maarten-baert*; fi
                                        ;;
                                    
                                    25)
                                        #RVM - smplayer gtk
                                        sudo add-apt-repository -yn ppa:rvm/smplayer
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/rvm*; fi
                                        ;;
                                    
                                    26)
                                        #RVM - smplayer qt4
                                        sudo add-apt-repository -yn ppa:rvm/smplayer-qt4
                                        if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/rvm*; fi
                                        ;;
                                    
                                    27)	
                                        #Sublimehq - Sublime text
                                        wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
                                        sudo apt install apt-transport-https -y
                                        echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
                                        ;;

                                #The rest are here merely to allow for expansion
                                    #			28)
                                                    #
                                    #				;;
                                    #
                                    #			29) 
                                                    #
                                    #				;;
                                    #
                                    #			30) 
                                                    #
                                    #				;;
                                    #
                                esac
                            done

                        # Updating the Cache after all PPAs have been set up.
                            echo "Updating the Apt Cache. Double check for any problems!"
                            sudo apt update

                    ;;

                A)
                    ;;

                C)
                    ;;

                D)
                    sudo apt install dialog
                    cmd1=(dialog --separate-output --checklist "Please Select Repos you want to install (only RPM Fusion compatible repos are included):" 22 76 16)
                    options1=(1 "Firefox-Nightly" off    # any option can be set to default to "on"
                        2 "deb-multimedia" off 
                        3 "Virtualbox" off
                        4 "Lutris" off
 
                    choices1=$("${cmd1[@]}" "${options1[@]}" 2>&1 >/dev/tty)
                    clear
                    for choice1 in $choices1;
                    do                   
                        case $choice1 in
                          
                            1)
                                #Firefox-Nightly
                                echo "Installing Firefox-Nightly Repository"
                                wget -O - http://v.s.cz/info@vitexsoftware.cz.gpg.key | sudo apt-key add -
                                echo "deb http://v.s.cz/ stable main" | sudo tee /etc/apt/sources.list.d/vitexsoftware.list
                                ;;

                            2)
                                #Deb-Multimedia
                                echo "Installing Deb-Multimedia Repository"
                                if [[ "$(lsb_release -sc)" == 'jessie' || "$(lsb_release -sc)" == 'wheezy' ]];
                                    then sudo sh -c 'echo "deb http://www.deb-multimedia.org $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list';
                                else sudo sh -c 'echo "deb http://www.deb-multimedia.org $(lsb_release -cs) main non-free" | sudo tee -a /etc/apt/sources.list';
                                fi
                                ;;

                            3)	
                                #Virtualbox
                                echo "Installing Virtualbox Repository"
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
                                sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list'
    		                    if [ $(lsb_release -sc) == "buster" ]; then sudo sed -i 's/buster/stretch/g' /etc/apt/sources.list.d/virtualbox*; fi
                                if [ $(lsb_release -sc) == "sid" ]; then sudo sed -i 's/sid/stretch/g' /etc/apt/sources.list.d/virtualbox*; fi
                                ;;
                                
                            4)
                                #Lutris
                                echo "Installing Lutris Repository"
                                echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_9.0/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                                wget -q http://download.opensuse.org/repositories/home:/strycore/Debian_9.0/Release.key -O- | sudo apt-key add -
                                ;;

                        esac
                    done

                    # Updating the Cache after all PPAs have been set up.
                        echo "Updating the Apt Cache."
                        sudo apt update
                    ;;

                F)
                    sudo apt install dialog
                    cmd1=(dialog --separate-output --checklist "Please Select Repos you want to install (only RPM Fusion compatible repos are included):" 22 76 16)
                    options1=(1 "fedora-workstation-repositories (PyCharm, Google Chrome, Nvidia drivers fedora28+, Steam client fedora28+" off    # any option can be set to default to "on"
                        2 "RPM Fusion" off 
                        3 "Virtualbox" off
                        4 "Lutris" off
 
                    choices1=$("${cmd1[@]}" "${options1[@]}" 2>&1 >/dev/tty)
                    clear
                    for choice1 in $choices1;
                    do                   
                        case $choice1 in
                          
                            1)
                                #fedora-workstation-repositories
                                echo "Installing fedora-workstation-repositories"
                                sudo dnf -y remove google-chrome-release
                                sudo dnf -y install fedora-workstation-repositories
                                ;;

                            2)
                                #RPM Fusion
                                echo "Installing RPM Fusion"
                                sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
                                ;;
                            3)	
                                #Virtualbox
                                echo "Installing Virtualbox Repository"
                                sudo wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | rpm --import -
                                sudo wget -q https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo -O /etc/yum.repos.d/virtualbox.repo
                                ;;
                                
                            4)
                                #Lutris
                                echo "Installing Lutris repo"
                                sudo dnf config-manager --add-repo "https://download.opensuse.org/repositories/home:strycore/Fedora_$FEDSUB/home:strycore.repo"
                                ;;

                        esac
                    done

                    # Updating the Cache after all PPAs have been set up.
                        echo "Updating the dnf Cache."
                        sudo dnf check-update
                    ;;

                O)
                    ;;

                *)
                    echo "Skipping this section due to faulty input"
                    ;;

            esac                        

        fi

    #Snaps and Flatpaks
        if [[ "$SNAPFLAT" == 'Y' || -z "$SNAPFLAT" ]];
        then
            echo "Installing Flatpak & Snaps"
            case $DISTBASE in
                U)
                    sudo add-apt-repository -yn ppa:alexlarsson/flatpak
		            if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/alexlarsson*; fi
                    sudo apt update && sudo apt -y install flatpak snapd
                    ;;

                A)
                    sudo pacman -S --needed --noconfirm snapd
                    sudo systemctl enable --now snapd.socket
                    sudo pacman -S --needed --noconfirm flatpak
                    ;;

                C)
                    sudo pacman -S --needed --noconfirm snapd
                    sudo systemctl enable --now snapd.socket
                    sudo pacman -S --needed --noconfirm flatpak
                    ;;

                D)
                    sudo apt update && sudo apt -y install flatpak snapd
                    ;;

                F)
                    sudo dnf -y install snapd
                    sudo ln -s /var/lib/snapd/snap /snap
                    sudo dnf -y install flatpak
                    ;;

                O)
                    if [ "$SUSESUB" == 'T' ];
                    then
                        sudo zypper addrepo --refresh http://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed/ snappy
                    else
                        sudo zypper addrepo --refresh http://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_42.3/ snappy
                    fi
                    sudo zypper install snapd
                    sudo systemctl enable --now snapd.socket
                    sudo zypper install flatpak
                    ;;

                *)
                    echo "Skipping this section due to faulty input"
                    ;;

            esac                
        fi

    #Additional Software Installation
        if [[ "$ADDAPPS" == 'Y' || -z "$ADDAPPS" ]];
        then
            echo "Installing Additional Software"
            cmd2=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
        	options2=(1 "Sublime Text" off    # any option can be set to default to "on"
        		2 "Simplenote" off
                3 "Leafpad" off
                4 "Terminology" off
                5 "Filezilla" off
                6 "Zoom Meeting Client" off
                7 "Telegram (SNAP)" off
                8 "Elementary Tweaks" off
                9 "Ubuntu Restricted Extras" off
                10 "SM Player Media Player" off
                11 "Gnome Tweak Tool" off
                12 "Google Chrome" off
                13 "Vivaldi" off
                14 "Firefox-Nightly Browser" off
                15 "GIMP" off
                16 "OBS-Studio" off
                17 "Kdenlive" off
                18 "Gnome Boxes" off
                19 "Virtualbox" off
                20 "Atom" off
                21 "Putty" off
                22 "Steam (Valve)" off
                23 "PIA VPN (Network Mgr Version)" off
                24 "Docky" off
                25 "Lutris" off
                26 "Hexchat" off
                27 "Shotwell" off
                28 "Cheese" off
                29 "Audacity" off
                30 "Guvcview (webcam settings)" off
                31 "Pithos (Pandora)" off
                32 "Gnome Shell" off
                33 "Gnome-do (search tool)" off
                34 "Discord (Snap)" off
                35 "Google Desktop Player (rocco)" off
                36 "Etcher" off
                37 "Tilix" off
                38 "Synology NAS Backup" off
                39 "KXStudio Jack Setup (Advanced Audio)" off
                40 "Catfish - File Search" off
                41 "Xfce Monitor Move Script" off
                42 "Thunderbird" off
                43 "Softmaker Office 2016" off
                44 "Oracle Java 10" off
                45 "Cairo-dock" off
                46 "Grub-Customizer" off
                47 "Samba File Systems" off
                48 "Compression Tools" off
                49 "Graphics Misc." off
                50 "Multimedia Misc." off
                51 "HPLIP" off
                52 "Overgrive" off
                53 "Ubuntu Kernel Update Utility" off
                54 "Git" on
                55 "Post Install Auto Clean Up & Update" off
#                56 "Hold for future use" off
#                57 "Hold for future use" off
                )
            choices2=$("${cmd2[@]}" "${options2[@]}" 2>&1 >/dev/tty)
            clear
            case $DISTBASE in
                U)
                    sudo apt update
                	sudo apt install dialog -y

                    for choice2 in $choices2
                    do
                        case $choice2 in
                        
                        1)
                            #Install Sublime Text*
                            echo "Installing Sublime Text"
                            if [ -e /etc/apt/sources.list.d/sublime-text.list ];
                            then
                                sudo apt install sublime-text -y
                            else
                                wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
                                sudo apt install -y apt-transport-https
                                echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
                                sudo apt update
                                sudo apt install sublime-text -y
                            fi
                            ;;

                        2)
                            #Simplenote
                            echo "Installing Simplenote"
                            wget https://github.com/Automattic/simplenote-electron/releases/download/v1.1.7/Simplenote-linux-1.1.7.deb
                            sudo dpkg -i Simplenote-linux-1.1.7.deb
                            sudo rm -rf Simplenote-linux-1.1.7.deb
                            ;;

                        3)	
                            #Install Leafpad
                            echo "Leafpad"
                            sudo apt install leafpad -y
                            ;;
                            
                        4)
                            #Terminology
                            echo "Installing Terminology"
                            sudo apt install terminology -y
                            ;;

                        5)
                            #Filezilla
                            echo "Filezilla not related to Godzilla"
                            sudo apt install filezilla -y
                            ;;
                        6)
                            #Zoom
                            echo "Installing Zoom Meeting Client"
                            echo "Installing dependency first First"				
                            sudo apt install libxcb-xtest0 -y
                            'cd ~/Downloads || return'				
                            wget https://zoom.us/client/latest/zoom_amd64.deb
                            sudo dpkg -i zoom_amd64.deb
                            sudo apt --fix-broken install -y
                            sudo rm -rf zoom_amd64.deb
                            ;;
                        7)
                            #Telegram
                            echo "Telegram Snap"
                            sudo snap install telegram-desktop
                            ;;
                        8)
                            #Elementary OS Tweaks
                            echo "Installing Elementary Tweaks"
                            sudo apt install software-properties-common -y
                            sudo apt update
                            sudo apt install elementary-tweaks -y
                            ;;
                        9)
                            #Ubuntu Restricted Extras
                            echo "Installing Ubuntu Restricted Extras"
                            sudo apt install ubuntu-restricted-extras -y
                            sudo apt --fix-broken install -y
                            ;;
                        10)
                            #SMPlayer
                            echo "SMPlayer"
                            sudo apt install smplayer -y
                            ;;
                        11)
                            #Gnome tweak tool
                            echo "Installing Gnome Tweak Tool"
                            sudo apt install gnome-tweak-tool -y
                            ;;
                        12)

                            #Chrome
                            echo "Installing Google Chrome"
                            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list'
                            sudo apt update 
                            sudo apt install google-chrome-stable -y
                            ;;
                        13)
                            #Vivaldi
                            echo "Installing Vivaldi"
                            'cd ~/Downloads || return'				
                            wget https://downloads.vivaldi.com/stable/vivaldi-stable_1.15.1147.64-1_amd64.deb
                            sudo dpkg -i vivaldi-stable_1.15.1147.64-1_amd64.deb
                            sudo apt install -f -y
                            rm -rf vivaldi-stable_1.15.1147.64-1_amd64.deb
                            ;;
                        14)

                            #Firefox Browser
                            echo "Firefox-Nightly"
                            if [ -e /etc/apt/sources.list.d/ubuntu-mozilla-daily-ubuntu-ppa-"$(lsb_release -sc)".list ];
                            then
                                sudo apt install firefox-trunk -y
                            else
                                sudo add-apt-repository -yn ppa:ubuntu-mozilla-daily/ppa
                                sudo apt update && sudo apt install firefox-trunk -y
                            fi
                            ;;
                        15)

                            #GIMP
                            echo "Installing GIMP"
                            if [ -e /etc/apt/sources.list.d/otto-kesselgulasch-ubuntu-gimp-"$(lsb_release -sc)".list ];
                            then
                                sudo apt install gimp -y
                            else
                                sudo add-apt-repository -yn ppa:otto-kesselgulasch/gimp
                                sudo apt update && sudo apt install gimp -y
				sudo apt --fix-broken install -y
                            fi
                            ;;
                        16)
                            #OBS Studio
                            echo "Installing OBS Studio"
                            sudo apt install ffmpeg -y
                            if [ -e "/etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-$(lsb_release -sc).list" ];
                            then
                                if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/obsproject*; fi
                                sudo apt install obs-studio -y
                            else
                                sudo add-apt-repository ppa:obsproject/obs-studio
                                if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/obsproject*; fi
                                sudo apt update && sudo apt install obs-studio -y
                            fi
                            ;;
                        17)

                            #Kdenlive
                            echo "Kdenlive"
                            sudo apt install kdenlive -y
                            sudo apt install breeze-icon-theme -y
                            sudo apt install vlc -y
                            ;;
                        18)
                            #Gnome Boxes
                            echo "Installing Gnome Boxes"
                            sudo apt install gnome-boxes -y
                            ;;

                        19)	#Virtualbox
                            echo "Installing Virtualbox"
                            if [ -e /etc/apt/sources.list.d/virtualbox.list ];
                            then
                                sudo apt install -y gcc make linux-headers-"$(uname -r)" dkms
                                sudo apt install virtualbox-5.2 -y
                            else
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
                                sudo sh -c 'echo deb http://download.virtualbox.org/virtualbox/debian "$(lsb_release -sc)" contrib | sudo tee -a /etc/apt/sources.list.d/virtualbox.list'
                                sudo apt -y install gcc make "linux-headers-$(uname -r)" dkms
                                sudo apt install virtualbox-5.2 -y
                            fi
                            ;;

                        20)	#Atom
                            echo "Installing Atom"				
                            'cd ~/Downloads || return'			
                            wget -O atom-amd64.deb https://atom.io/download/deb			
                            sudo dpkg -i atom-amd64.deb
                            sudo apt install -f -y
                            sudo rm -rf atom-amd64.deb
                            sudo apm install atom-html-preview
                            ;;

                        21)	#Putty
                            echo "Putty"
                            sudo apt install putty -y
                            ;;

                        22)	#Steam
                            echo "Installing Steam"				
                            sudo apt install steam -y
                            ;;

                        23)	#PIA VPN
                            echo "Installing PIA VPN Network Manager Version"
                            'cd ~/Downloads || return'				
                            wget https://www.privateinternetaccess.com/installer/install_ubuntu.sh
                            sudo sh ./install_ubuntu.sh
                            echo "After entering username, go to network manager and turn on VPN and select from PIA locations, enter password and boom!"
                            ;;

                        24)	#Docky
                            echo "Installing Docky"
                            sudo apt install docky -y
                            ;;

                        25)	#Lutris
                            echo "Installing Lutris"
                            if [ -e /etc/apt/sources.list.d/lutris.list ];
                            then
                                sudo apt install lutris -y
                            else
                                ver=$(lsb_release -sr); if [ "$ver" != "18.04" ] && [ "$ver" != "17.10" ] && [ "$ver" != "17.04" ] && [ "$ver" != "16.04" ]; then ver="18.04"; fi
                                wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_"$ver"/Release.key -O- | sudo apt-key add -
                                echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                                sudo apt update && sudo apt install lutris -y
                            fi
                            ;;

                        26)	#Hexchat
                            echo "Installing Hexchat"
                            sudo apt install hexchat -y
                            ;;

                        27)	#Shotwell
                            echo "Installing Shotwell"
                            sudo apt install shotwell -y
                            ;;

                        28)	#Cheese
                            echo "Installing Cheese"
                            sudo apt install cheese -y
                            ;;

                        29) 
                            #Audacity
                            echo "installing Audacity"
                            sudo apt install audacity -y
                            ;;

                        30) 
                            #Guvcview
                            echo "installing Guvcview"
                            sudo apt install -y libgslcblas0 guvcview
                            ;;

                        31) 
                            #Pithos
                            echo "installing Pithos"
                            sudo apt install pithos -y
                            ;;
                        
                        32) 
                            #Gnome Shell
                            echo "installing Gnome Shell"
                            sudo apt install chrome-gnome-shell -y
                            ;;
                        
                        33) 
                            #Gnome-do
                            echo "Installing GnomeDo"
                            sudo apt install -y gnome-do gnome-do-plugins
                            ;;
                        34)
                            #Discord
                            sudo snap install discord
                            ;;

                        35) 
                            #Google Desktop Player
                            echo "Installing Google Desktop Player"
                            'cd ~/Downloads || return'
                            wget -O google-play-music-desktop-player.deb https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/download/v4.5.0/google-play-music-desktop-player_4.5.0_amd64.deb
                            sudo dpkg -i google-play-music-desktop-player*.deb
                            sudo apt install -f -y
                            sudo rm -rf google-play-music-desktop-player*.deb
                            ;;

                        36) 
                            #Etcher ISO Creator
                            echo "Installing Etcher"
                            sudo apt install -y etcher-electron
                            ;;

                        37) 
                            #Tilix (Tiling Terminal)
                            echo "Installing Tilix"
                            sudo apt install tilix -y
                            ;;

                        38) 
                            #Synology NAS Assistant & Backup
                            echo "Installing Syn Assist, CloudStation Backup"
                            wget -O synassistant.deb https://global.download.synology.com/download/Tools/Assistant/6.1-15163/Ubuntu/x86_64/synology-assistant_6.1-15163_amd64.deb
                            sudo dpkg -i synassistant*.deb
                            sudo apt install -f -y
                            sudo rm -rf synassistant*.deb
                            wget -O cloudback.deb https://global.download.synology.com/download/Tools/CloudStationBackup/4.2.6-4408/Ubuntu/Installer/x86_64/synology-cloud-station-backup-4408.x86_64.deb
                            sudo dpkg -i cloudback*.deb
                            sudo apt install -f -y
                            sudo rm -rf cloudback*.deb
                            ;;

                        39) 
                            #Advanced Jack Audio Setup
                            echo "installing KXStudio Jack"
                            # Get user name for permissions
                            #echo "Enter your username"
                            #read -r -pr 'Username: ' uservar
                            # Install required dependencies if needed
                            sudo apt install apt-transport-https software-properties-common wget
                            wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.5.1~kxstudio3_all.deb
                            # Install it
                            sudo dpkg -i kxstudio-repos_9.5.1~kxstudio3_all.deb
                            sudo apt install libglibmm-2.4-1v5 -y
                            wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb
                            sudo dpkg -i kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb
                            currentuser=$(who | awk 'NR==1{print $1}')
                                    sudo usermod -a -G audio "$currentuser"
                                    sudo apt update && sudo apt upgrade -y
                                    sudo apt install jackd2-firewire -y
                                    sudo apt install -y jackd2 carla-git cadence non-mixer pulseaudio-module-jack mididings -y
                                    # Download auto script github
                                    'cd ~/ || return'
                                    mkdir jacksetup
                                    'cd ~/jacksetup || return'
                                    wget https://raw.githubusercontent.com/Skrappjaw/audio-scripts/master/start_jack.sh
                                    sudo chmod +x ~/jacksetup/start_jack.sh
                                    sudo chown -R "$currentuser":"$currentuser" ~/jacksetup
                            # Optional to put script into autostart
                            #cd ~/
                            #cp ~/jacksetup/start_jack.sh /etc/init.d/
                            #update-rc.d start_jack.sh defaults
                            ;; 
                        
                        40) 
                            #Install Catfish
                            echo "Installing Catfish"
                            sudo apt install catfish -y
                            ;;

                        41) 
                            #Install monitor move window script Xfce
                            echo "Monitor move window script"
                            wget https://raw.githubusercontent.com/dasgeekchannel/move-to-next-monitor/master/move-to-next-monitor
                            'cd ~/Documents || return'
                            currentuser=$(who | awk 'NR==1{print $1}')
                            sudo chmod +x ~/Documents/move-to-next-monitor
                            sudo chown -R "$currentuser":"$currentuser" ~/Documents/move-to-next-monitor
                            ;;

                        42)	
                            #Install Mozilla Thunderbird
                            echo "Installing Thunderbird"
                            if [ -e /etc/apt/sources.list.d/mozillateam-ubuntu-thunderbird-next-"$(lsb_release -sc)".list ];
                            then
                                if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/mozillateam*; fi
                                sudo apt install thunderbird -y
                            else
                                sudo add-apt-repository -yn ppa:mozillateam/thunderbird-next
                                if [ $(lsb_release -sc) == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/mozillateam*; fi
                                sudo apt update && sudo apt install thunderbird -y
                            fi
                            ;;

                        43)
                            #Install Softmaker Office 2016
                            echo "Installing Softmaker Office 2016"
                            'cd ~/Downloads || return'
                            wget http://www.softmaker.net/down/softmaker-office-2016_761-01_i386.deb
			    #Install Dependencies
                            sudo dpkg --add-architecture i386
                            sudo apt install -y gcc-8-base:i386 libbsd0:i386 libc6:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi6:i386 libgcc1:i386 libgl1:i386
                            sudo apt install -y libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libice6:i386 libidn11:i386 libidn2-0:i386 libllvm6.0:i386 libpciaccess0:i386 libsensors4:i386 libsm6:i386
                            sudo apt install -y libstdc++6:i386 libtinfo6:i386 libunistring2:i386 libuuid1:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386 libxcb1:i386
                            sudo apt install -y libxdamage1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxmu6:i386 libxrandr2:i386 libxrender1:i386 libxshmfence1:i386 libxt6:i386 libxxf86vm1:i386 zlib1g:i386
                            sudo dpkg -i softmaker-office-2016_761-01_i386.deb
                            sudo rm ./softmaker-office-2016_761-01_i386.deb
                            ;;

                        44)
                            #Install Oracle Java 10 and set Runtime
                            echo "Installing Oracle Java 10"
                            if [ -e /etc/apt/sources.list.d/linuxuprising-ubuntu-java-"$(lsb_release -sc)".list ];
                            then
                                echo oracle-java10-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
                                sudo apt update && sudo apt install -y oracle-java10-installer
                            else
                                sudo add-apt-repository -yn ppa:linuxuprising/java
                                echo oracle-java10-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
                                sudo apt update && sudo apt install -y oracle-java10-installer
                            fi
                            ;;

                        45)
                            #Install Cairo-dock
                            sudo apt install cairo-dock -y
                            ;;

                        46)
                            #Install Grub-Customizer
                            echo "Installing Grub-Customizer"
                            if [ -e /etc/apt/sources.list.d/danielrichter2007-ubuntu-grub-customizer-"$(lsb_release -sc)".list ];
                            then
                               sudo apt install grub-customizer -y
                            else 
                                sudo add-apt-repository -yn ppa:danielrichter2007/grub-customizer
                                sudo apt update && sudo apt install grub-customizer -y
                            fi
                            ;;

                        47)
                            #Install Samba File Systems
                            echo "Installing File Systems for Samba"
                            sudo apt install -y nfs-common fusesmb samba python-smbc cifs-utils exfat-utils
                            ;;

                        48)
                            #Install Compression Tools
                            echo "Installing Compression Tools"
                            sudo apt install -y engrampa p7zip-rar arj lzip rar unrar rpm2cpio rzip unace
                            ;;

                        49)
                            #Install Misc. Graphics Tools
                            echo "Installing Misc. Graphics Tools"
                            sudo apt install -y darktable gwenview inkscape okular skanlite
                            ;;

                        50)
                            #Install Misc. Multimedia Tools
                            echo "Installing Misc. Multimedia Tools"
                            sudo apt install -y k3b openshot simplescreenrecorder
                            ;;

                        51)
                            #Install HPLIP
                            echo "Installing HPLIP"
                            sudo apt install -y hplip xsane
                            ;;

                        52)
                            #Install  Overgrive
                            echo "Installing Overgrive"
                            sudo add-apt-repository universe && sudo apt update
                            wget https://www.thefanclub.co.za/sites/default/files/public/overgrive/overgrive_3.2.3_all.deb
                            # Steps to fix Overgrive fail to install/start
                                wget https://bootstrap.pypa.io/get-pip.py
                                sudo python2.7 get-pip.py
                                sudo pip2.7 install msgpack-python
                                sudo pip2.7 install --upgrade google-api-python-client
                                sudo pip2.7 install --upgrade oauth2client
                            sudo dpkg -i overgrive_3.2.3_all.deb
                            ;;

                        53)
                            #Ubuntu Kernel Update Utility
                            echo "Installing UKUU"
                            sudo apt install -y ukuu
                            ;;

                        54)	
                            #Git
                            echo "Installing Git"
                            sudo apt install -y git
                            ;;

                        55)
                            #Clean up
                            echo "Running Clean Up And Update"
                            sudo apt update
                            sudo apt full-upgrade -y
                            sudo apt autoremove
                            ;;
#
#                        56)
                            #
#                            ;;
#
#                        57)
                            #
#                            ;;
#
                    esac
                done

                    ;;

                A)
                    ;;

                C)
                    ;;

                D)
                    ;;

                F)
                    ;;

                O)
                    ;;

                 *)
                    echo "Skipping this section due to faulty input"
                    ;;

            esac
    fi


    #Update hosts file
		echo "I would suggest updating your hosts file for security"
        echo "You might consider using https://someonewhocares.org/hosts/hosts as a base"
				
	#Reboot Reminder
		echo "Don't forget to reboot before updating to assure proper disk mounting!!!"

fi

