#!/bin/bash
# Distro Hopper's Friend
# David F Muller
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# ~David F Muller
# Version 0.7.6-beta

# Test for bash shell
    if [ "$0" != "/bin/bash" ]; then /bin/bash; fi
#function for symlinking files and folders from a seperate home partition
    symlink_setup () {
        if [ -e "$user_data_mountpoint/$1" ]; then
            if [ -e "/home/$user_name/$1" ]; then
                sudo rm -Rf "/home/$user_name/$1"; fi
        sudo ln -s "$user_data_mountpoint/$1" "/home/$user_name"
        fi
    }
#Functions for adding repos
    reg_repo_install () {
           case $BaInCo in
                dnf)
                    ;;
                pacman)
                    for k in "${arch_repo_keys[@]}"; do
                        sudo pacman-key --recv-keys "$k" && sudo pacman-key --lsign-key "$k"
                    done
                    curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
                    for i in "${arch_repos[@]}"; do
                        echo "$user_sudo_password" | sudo -S sh -c "echo \"$i\" >&- >> /etc/pacman.conf"
                    done
                    ;;
                zypper)
                    ;;
                apt)
                    for i in "${regular_repos[@]}"; do
                        sudo add-apt-repository -yn $i    
                    done
                    ;;
            esac
    }

    oddball_repo_install () {
           case $BaInCo in
                dnf)
                    ;;
                zypper)
                    ;;
                apt)
                    for i in "${oddball_repos[@]}"; do
                        case $i in
                            etcher)
                                echo "deb https://dl.bintray.com/resin-io/debian stable etcher" | sudo tee /etc/apt/sources.list.d/etcher.list
                                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
                                ;;
                            simplescreenrecorder)
                                sudo add-apt-repository -yn ppa:maarten-baert/simplescreenrecorder
                                if [ "$(lsb_release -sc)" != "bionic" ]; then sudo sed -i 's/$(lsb_release -sc)/bionic/g' /etc/apt/sources.list.d/maarten-baert*; fi
                                ;;
                            sublime)
                                wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
                                sudo apt install apt-transport-https -y
                                echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
                                ;;
                            pepp9)
                                sudo add-apt-repository -yn ppa:peppermintos/p9-release
                                if [ "$(lsb_release -sc)" != "bionic" ]; then sudo sed -i 's/$(lsb_release -sc)/bionic/g' /etc/apt/sources.list.d/peppermint*; fi
                                ;;
                            steam)
                                sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B05498B7
                                sudo sh -c 'echo "deb http://repo.steampowered.com/steam/ precise steam" | sudo tee -a /etc/apt/sources.list.d/steam.list'
                                ;;
                            vbox)
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
                                sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee -a /etc/apt/sources.list.d/virtualbox.list'
                                if [ "$(lsb_release -sc)" == "buster" ]; then sudo sed -i 's/buster/stretch/g' /etc/apt/sources.list.d/virtualbox*; fi
                                if [ "$(lsb_release -sc)" == "sid" ]; then sudo sed -i 's/sid/stretch/g' /etc/apt/sources.list.d/virtualbox*; fi
                                ;;
                            vcode)
                                curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
                                sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
                                sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
                                ;;
                            lutris)
                                if [[ "$base_distro" == "U" ]]; then
                                    if [ "$ver" != "18.10" ] && [ "$ver" != "18.04" ] && [ "$ver" != "17.10" ] && [ "$ver" != "17.04" ] && [ "$ver" != "16.04" ]; then ver="18.04"; fi
                                    echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                                    wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_"$ver"/Release.key -O- | sudo apt-key add -
                                else
                                    echo "deb http://download.opensuse.org/repositories/home:/strycore/Debian_9.0/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                                    wget -q http://download.opensuse.org/repositories/home:/strycore/Debian_9.0/Release.key -O- | sudo apt-key add -
                                fi
                                ;;
                            multimedia)
                                if [[ "$(lsb_release -sc)" == 'jessie' || "$(lsb_release -sc)" == 'wheezy' ]]; then
                                    sudo sh -c 'echo "deb http://www.deb-multimedia.org $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list'
                                else sudo sh -c 'echo "deb http://www.deb-multimedia.org $(lsb_release -cs) main non-free" | sudo tee -a /etc/apt/sources.list'
                                fi
                                ;;
                            nightly-fox)
                                wget -O - http://v.s.cz/info@vitexsoftware.cz.gpg.key | sudo apt-key add -
                                echo "deb http://v.s.cz/ stable main" | sudo tee /etc/apt/sources.list.d/vitexsoftware.list
                                ;;
                        esac
                    done
                    ;;
            esac   
    }
#Functions for installing additional apps
    app_installer () {
        $InCommand "$1"
    }

    special_apps_install () {
        case $1 in
            lutris)
                if [[ "$BaInCo" == "apt" ]]; then
                    if [[ ! -f /etc/apt/sources.list.d/lutris.list ]]; then
                        if [ "$ver" != "18.10" ] && [ "$ver" != "18.04" ] && [ "$ver" != "17.10" ] && [ "$ver" != "17.04" ] && [ "$ver" != "16.04" ]; then ver="18.04"; fi
                        echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                        wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_"$ver"/Release.key -O- | sudo apt-key add -
                    fi
                fi
                $InCommand lutris
                ;;
            vbox)
                ;;
            etcher)
                if [[ ! -f /etc/apt/sources.list.d/etcher.list ]]; then
                    echo "deb https://dl.bintray.com/resin-io/debian stable etcher" | sudo tee /etc/apt/sources.list.d/etcher.list
                    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
                fi
                $InCommand etcher-electron                
                ;;
        esac
    }
#Prep needed arrays
    home_folders=()
    install_apps=()
    special_installs=()
    regular_repos=()
    oddball_repos=()
    arch_repo_keys=(932BA3FA0C86812A32D1F54DAB5964AEB9FEDDDC 313F5ABD 4B4E7A9523ACD201 7448C890582975CD)
    arch_repos=(" " "#Third party repos"
" " "[qt-debug]" "Server = https://qutebrowser.org/qt-debug/$arch"
" " "[seblu]" "Server = http://al.seblu.net/$repo/$arch"
" " "[archlinuxfr]" "SigLevel = Never" "Server = http://repo.archlinux.fr/$arch"
" " "[heftig]" "SigLevel = Never" "Server = https://pkgbuild.com/~heftig/repo/$arch"
" " "[jkanetwork]" "SigLevel = Never" "Server = http://repo.jkanetwork.com/repo/$repo/"
" " "[mesa-git]" "SigLevel = Never" "Server = https://pkgbuild.com/~lcarlier/$repo/$arch"
" " "[jlk]" "Server = http://jlk.fjfi.cvut.cz/arch/repo"
" " "[ownstuff]" "SigLevel = PackageOptional" "Server = http://martchus.no-ip.biz/repo/arch/$repo/os/$arch"
" " "[xyne-x86_64]" "SigLevel = PackageOptional" "Server = https://xyne.archlinux.ca/repos/xyne"
" " "[dx37essentials]" "SigLevel = PackageOptional" "Server = https://dx37.gitlab.io/$repo/$arch"
" " "[miffe]" "SigLevel = PackageOptional" "Server = https://arch.miffe.org/$arch/"
" " "[DEB_Arch_Extra]" "SigLevel = Optional TrustAll" "Server = https://mega.nz/linux/MEGAsync/Arch_Extra/$arch"
" " "[sublime-text]" "Server = https://download.sublimetext.com/arch/stable/x86_64" " ")

#Main body of script
    echo "Welcome to the Distro Hopper's Friend"
    echo "If you have any doubts about me or this script, please review the code before running"
    echo "(You really should do this anyway! ;-) )"
    echo
    echo "OK then, let's get started!"
    echo "Sudo password is required for certain commands in this script."
    echo "Entering an incorrect password will cause the script to crash."
    read -r -s -p "Enter password: " user_sudo_password && printf "\n"
    echo "$user_sudo_password" | sudo -S sh -c "echo \"$USER ALL=(ALL) NOPASSWD: ALL\" >&- > /etc/sudoers.d/90-$USER"
#Gather Basic Info
    input_check="N"
    while [[ "$input_check" == "N" ]]; do
        read -r -p "What is your user name?: " user_name
        if [[ "$user_name" == "$USER" ]]; then input_check="Y"
        else
            echo " You are logged in as $USER, but you entered $user_name. This mismatch will cause issues."
            read -r -p "Do you wish to re-enter your user name (Y/n [No will exit the script])? " reenter_name
            reenter_name=${reenter_name^}
            if [[ -z "$reenter_name" ]]; then reenter_name="Y"; fi
            if [[ "$reenter_name" != "Y" ]]; then
                sudo rm -f "/etc/sudoers.d/90-$USER"
                sudo -k
                exit 1; fi
        fi
    done
    user_name=${user_name,,}
#Auto Entry of Sudo Password in the Terminal
    input_check="N"
    while [[ "$input_check" == "N" ]]; do
        read -r -p "Do you want to auto enter your sudo password when in a terminal? (y/N): " auto_user_password
        auto_user_password=${auto_user_password^}
        if [[ -z "$auto_user_password" ]]; then auto_user_password="N" && input_check="Y"
        elif [[ "$auto_user_password" == "Y" || "$auto_user_password" == "N" ]]; then input_check="Y"
        else echo "Sorry I didn't understand that."; fi
    done
#Dedicated Data/Home Partition
    input_check="N"
    while [[ "$input_check" == "N" ]]; do
        read -r -p "Do you have a seperate/dedicated data partition that holds your Home folders? (Y/n): " seperate_data_partition
        seperate_data_partition=${seperate_data_partition^}
        if [[ -z "$seperate_data_partition" ]]; then seperate_data_partition="Y" && input_check="Y"
        elif [[ "$seperate_data_partition" == "Y" || "$seperate_data_partition" == "N" ]]; then input_check="Y"
        else echo "Sorry I didn't understand that."; fi
    done
#Determine Base Distro
    declare -A osInfo;
    osInfo[/etc/redhat-release]=dnf
    osInfo[/etc/arch-release]=pacman
    osInfo[/etc/gentoo-release]=emerge
    osInfo[/etc/SuSE-release]=zypper
    osInfo[/etc/debian_version]=apt

    for i in "${!osInfo[@]}"; do
        if [[ -f "$i" ]]; then
            #Set the Base Install Command
            BaInCo="${osInfo[$i]}"
        fi
    done
#Set Install Command
    case $BaInCo in
        dnf)
            InCommand="sudo dnf install"
            RefreshRepos="sudo dnf check-update"
            UpGradeCommand="sudo dnf -y system-upgrade"
            $InCommand -y dialog curl
            read -r -p "What version number of Fedora is this distro based on? " fedora_base
            ;;
        pacman)
#Making sure yay-bin is installed
            echo "Installing yay-bin (run as yay) for easier AUR access"
            mkdir ./Installer
            cd Installer || return
            wget https://aur.archlinux.org/cgit/aur.git/snapshot/yay-bin.tar.gz
            tar -xvf ./yay-bin.tar.gz
            cd yay-bin || return
            makepkg -i --noconfirm --needed
            cd .. || return
            sudo rm -fR ./yay-bin
            cd .. || return
            sudo rm -fR ./Installer
            yay --editmenu --nodiffmenu --save
            InCommand="yay -S --needed"
            RefreshRepos="sudo pacman -Syy"
            UpGradeCommand="yay -Syyu --noconfirm"
            $InCommand --noconfirm dialog curl reflector
            sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist
            ;;
        emerge)
            InCommand="sudo emerge --ask"
            UpGradeCommand="sudo emerge --update --deep --with-bdeps=y @world"
            ;;
        zypper)
            InCommand="sudo zypper in"
            RefreshRepos="sudo zypper ref"
            UpGradeCommand="sudo zypper -y dist-upgrade"
            input_check="N"
            while [[ "$input_check" == "N" ]]; do
                read -r -p "Is this distro based on Leap or Tumbleweed (L/t)? " suse_base
                suse_base=${suse_base^}
                if [[ -z "$suse_base" ]]; then suse_base="L" && input_check="Y"
                elif [[ "$suse_base" == "L" || "$suse_base" == "T" ]]; then input_check="Y"
                else echo "Sorry I didn't understand that."; fi
                $InCommand -y dialog curl
            done
            ;;
        apt)
            InCommand="sudo apt install"
            RefreshRepos="sudo apt update"
            UpGradeCommand="sudo apt update && sudo apt dist-upgrade"
            $InCommand -y dialog curl
            input_check="N"
            while [[ "$input_check" == "N" ]]; do
                read -r -p "Is this distro Ubuntu or Debian based (U/d)? " base_distro
                base_distro=${base_distro^}
                if [[ -z "$base_distro" ]]; then base_distro="U" && input_check="Y"
                elif [[ "$base_distro" == "U" || "$base_distro" == "D" ]]; then input_check="Y"
                else echo "Sorry I didn't understand that."; fi
            done
            ;;
    esac
#Additional PPAs and/or Repositories
    echo "Included in this script is the option to install 3rd party repositories that I have found useful."
    input_check="N"
    while [[ "$input_check" == "N" ]]; do
        read -r -p "Would you like to install additional PPAs/Repositories (Currently only for Ubuntu, Debian, Arch and Fedora)? (Y/n): " additional_repos
        additional_repos=${additional_repos^}
        if [[ -z "$additional_repos" ]]; then additional_repos="Y" && input_check="Y"
        elif [[ "$additional_repos" == "Y" || "$additional_repos" == "N" ]]; then input_check="Y"
        else echo "Sorry I didn't understand that."; fi
    done
#Snaps and Flatpaks
    echo "Would you like to enable Snaps and Flatpaks?"
    input_check="N"
    while [[ "$input_check" == "N" ]]; do
        read -r -p "These are required for some of the Additional Software Installs (Y/n): " add_snaps_flatpaks
        add_snaps_flatpaks=${add_snaps_flatpaks^}
        if [[ -z "$add_snaps_flatpaks" ]]; then add_snaps_flatpaks="Y" && input_check="Y"
        elif [[ "$add_snaps_flatpaks" == "Y" || "$add_snaps_flatpaks" == "N" ]]; then input_check="Y"
        else echo "Sorry I didn't understand that."; fi
    done
#Additional Software
    input_check="N"
    while [[ "$input_check" == "N" ]]; do
        read -r -p "Would you like to install additional software? (Y/n): " additional_apps
        additional_apps=${additional_apps^}
        if [[ -z "$additional_apps" ]]; then additional_apps="Y" && input_check="Y"
        elif [[ "$additional_apps" == "Y" || "$additional_apps" == "N" ]]; then input_check="Y"
        else echo "Sorry I didn't understand that."; fi
    done
#End of Gathering Info

#Start of Actual Work
    echo "OK then, thats all I need for now, lets get started!"
#Seperate Home/Data Partition
    if [[ "$seperate_data_partition" == 'Y' ]]; then
        user_data_mountpoint=/home/$user_name/.home
        read -r -p "What is the absolute path (i.e. /dev/sda1) of your data/home partition?: " user_data_device
        user_data_device=${user_data_device,,}
        read -r -p "What is the filesystem (i.e. ext4) of your data/home partition?: " user_data_filesystem
        user_data_UUID=$( blkid -s UUID -o value "$user_data_device" )
        sudo echo "UUID=$user_data_UUID $user_data_mountpoint $user_data_filesystem users,exec,rw,auto,noatime 0 2" | sudo tee -a /etc/fstab
#Setup Directories for Mounting
        echo "Creating directory for mounting"
        mkdir "$user_data_mountpoint"
#Setup home folder
        echo "Mounting, setting up, and linking home folder"
        sudo mount "$user_data_device" "$user_data_mountpoint"
#Get list of files/folders to simlimk
        echo "Enter the names of all files and folders you wished linked from your home partition (Press Cntrl-D when finished): "
        while read -r HOMELINKS; do
            home_folders+=("$HOMELINKS")
        done
        echo "These are the files/folders which will be linked : ${home_folders[*]}"
#Remove original folders and set symbolic links
        for i in "${home_folders[@]}"; do
            symlink_setup "$i"
        done
#Assuring ownership of the new links
            sudo chown -R "$user_name:$user_name" "/home/$user_name"
    fi

#Setting up additional PPAs and other Repositories
        if [[ "$additional_repos" == 'Y' || -z "$additional_repos" ]];
        then
            case $BaInCo in
                apt)
                    if [[ $base_distro == "U" ]]; then
                    #Base Repos
                        regular_repos+=(main restricted universe multiverse)
                    # Warning
                        echo "Adding additional PPAs"
                        echo "BE WARNED - Not all PPAs have release pages for all versions of Ubuntu. Be sure to verify and correct any issues after installation!"
                    # PPA Installation Commands
                        ubuntu_ppas=(dialog --separate-output --checklist "Please Select PPAs you want to install:" 22 76 16)
                        options1=(1 "Canonical Kernal Team" off    # any option can be set to default to "on"
                            2 "Daniel Richter - grub-customizer" off 
                            3 "Etcher" off
                            4 "Nvidia Drivers" off
                            5 "Linux Uprising - Oracle Java" off
                            6 "Lutris" off
                            7 "Oibaf - open video drivers for radeon, intel and nvidia" off
                            8 "Sarnex - Wine + Gallium Nine" off
                            9 "Maarten Baert - simplescreenrecorder" off
                            10 "RVM - smplayer gtk & qt5" off
                            11 "RVM - smplayer qt4" off
                            12 "Sublime Text & Sublime Merge" off
                            13 "Firefox-Nightly (firefox-trunk)" off
                            14 "Thunderbird Beta" off
                            15 "OBS Project" off
                            16 "Otto Kesselgulasch - Gimp" off
                            17 "Peppermint 9" off
                            18 "Steam" off
                            19 "Tony George - Timeshift etc" off
                            20 "Virtualbox" off
                            21 "Visual Studio Code" off
                            22 "WebUpd8 Team" off
                            23 "XFCE - xubuntu-dev-extra" off
                            24 "XFCE - xubuntu-dev-experimental" off
                            25 "KDE - kubuntu backports" off)

                        selected_ubuntu_ppas=$("${ubuntu_ppas[@]}" "${options1[@]}" 2>&1 >/dev/tty) && clear
                        for selected_ubuntu_ppa in $selected_ubuntu_ppas; do                   
                            case $selected_ubuntu_ppa in
                                1)  regular_repos+=(ppa:canonical-kernal-team/ppa) ;;
                                2)  regular_repos+=(ppa:danielrichter2007/grub-customizer) ;;
                                3)  oddball_repos+=(etcher) ;;
                                4)  regular_repos+=(ppa:graphics-drivers/ppa) ;;
                                5)  regular_repos+=(ppa:linuxuprising/java) ;;
                                6)  oddball_repos+=(lutris) ;;
                                7)  regular_repos+=(ppa:oibaf/graphics-drivers) ;;
                                8)  regular_repos+=(ppa:commendsarnex/winedri3) ;;
                                9)  oddball_repos+=(simplescreenrecorder) ;;
                                10) regular_repos+=(ppa:rvm/smplayer) ;;
                                11) regular_repos+=(ppa:rvm/smplayer-qt4) ;;
                                12) oddball_repos+=(sublime) ;;
                                13) regular_repos+=(ppa:ubuntu-mozilla-daily/ppa) ;;
                                14) regular_repos+=(ppa:mozillateam/thunderbird-next) ;;
                                15) regular_repos+=(ppa:obsproject/obs-studio) ;;
                                16) regular_repos+=(ppa:otto-kesselgulasch/gimp) ;;
                                17) oddball_repos+=(pepp9) ;;
                                18) oddball_repos+=(steam) ;;
                                19) regular_repos+=(ppa:teejee2008/ppa) ;;
                                20) oddball_repos+=(vbox) ;;
                                21) oddball_repos+=(vcode) ;;
                                22) regular_repos+=(ppa:webupd8team/y-ppa-manager) ;;
                                23) regular_repos+=(ppa:xubuntu-dev/extras) ;;
                                24) regular_repos+=(ppa:xubuntu-dev/experimental) ;;
                                25) regular_repos+=(ppa:kubuntu-ppa/backports) ;;
                            esac
                        done
                    else
                        debian_repos=(dialog --separate-output --checklist "Please Select Repos you want to install (only RPM Fusion compatible repos are included):" 22 76 16)
                        options2=(1 "Firefox-Nightly" off    # any option can be set to default to "on"
                            2 "deb-multimedia" off 
                            3 "Virtualbox" off
                            4 "Lutris" off
                            5 "Visual Studio Code" off)
                        selected_debian_repos=$("${debian_repos[@]}" "${options2[@]}" 2>&1 >/dev/tty) && clear
                        for selected_debian_repo in $selected_debian_repos; do                   
                            case $selected_debian_repo in
                                1) oddball_repos+=(nightly-fox) ;;
                                2) oddball_repos+=(multimedia) ;;
                                3) oddball_repos+=(vbox) ;;
                                4) oddball_repos+=(lutris) ;;
                                5) oddball_repos+=(vcode) ;;
                            esac
                        done
                    fi
                    reg_repo_install && oddball_repo_install
                    echo "Updating the Apt Cache. Check for any errors for later correction."
                    "$RefreshRepos"
                    ;;
                pacman)
                    reg_repo_install
                    echo "Updating the repos. Check for any errors for later correction."
                    "$RefreshRepos"
                    ;;
                dnf)
                    sudo apt install dialog
                    fedora_repos=(dialog --separate-output --checklist "Please Select Repos you want to install (only RPM Fusion compatible repos are included):" 22 76 16)
                    options3=(1 "fedora-workstation-repositories (PyCharm, Google Chrome, Nvidia drivers fedora28+, Steam client fedora28+" off    # any option can be set to default to "on"
                        2 "RPM Fusion" off 
                        3 "Virtualbox" off
                        4 "Lutris" off)
                    selected_fedora_repos=$("${fedora_repos[@]}" "${options3[@]}" 2>&1 >/dev/tty) && clear
                    for selected_fedora_repo in $selected_fedora_repos; do                   
                        case $selected_fedora_repo in
                            1) sudo dnf -y remove google-chrome-release
                               sudo dnf -y install fedora-workstation-repositories
                               ;;
                            2) sudo dnf install "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"
                               ;;
                            3) sudo wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | rpm --import -
                               sudo wget -q https://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo -O /etc/yum.repos.d/virtualbox.repo
                               ;;
                            4) sudo dnf config-manager --add-repo "https://download.opensuse.org/repositories/home:strycore/Fedora_$fedora_base/home:strycore.repo"
                               ;;
                        esac
                    done
                    # Updating the Cache after all PPAs have been set up.
                        echo "Updating the dnf Cache."
                        sudo dnf check-update
                    ;;

                O)
                    ;;
            esac                        

        fi

    #Snaps and Flatpaks
        if [[ "$add_snaps_flatpaks" == 'Y' || -z "$add_snaps_flatpaks" ]];
        then
            echo "Installing Flatpak & Snaps"
            case $BaInCo in
                apt)
                    if [[ "$base_distro" == "U" ]]; then sudo add-apt-repository -yn ppa:alexlarsson/flatpak; fi
                    $RefreshRepos && $InCommand -y flatpak snapd
                    ;;

                A)
                    sudo pacman -S --needed --noconfirm snapd
                    sudo systemctl enable --now snapd.socket
                    sudo pacman -S --needed --noconfirm flatpak
                    ;;

                C)
                    sudo pacman -S --needed --noconfirm snapd
                    sudo systemctl enable --now snapd.socket
                    sudo pacman -S --needed --noconfirm flatpak
                    ;;

                D)
                    sudo apt update && sudo apt -y install flatpak snapd
                    ;;

                F)
                    sudo dnf -y install snapd
                    sudo ln -s /var/lib/snapd/snap /snap
                    sudo dnf -y install flatpak
                    ;;

                O)
                    if [ "$SUSESUB" == 'T' ];
                    then
                        sudo zypper addrepo --refresh http://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed/ snappy
                    else
                        sudo zypper addrepo --refresh http://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_42.3/ snappy
                    fi
                    sudo zypper install snapd
                    sudo systemctl enable --now snapd.socket
                    sudo zypper install flatpak
                    ;;

                *)
                    echo "Skipping this section due to faulty input"
                    ;;

            esac                
        fi

    #Additional Software Installation
        if [[ "$additional_apps" == 'Y' || -z "$additional_apps" ]];
        then
            echo "Installing Additional Software"
            cmd4=(dialog --separate-output --checklist "Please Select Software you want to install:" 22 76 16)
        	options4=(1 "Sublime Text" off    # any option can be set to default to "on"
        		2 "Simplenote" off
                3 "Leafpad" off
                4 "Terminology" off
                5 "Filezilla" off
                6 "Zoom Meeting Client" off
                7 "Telegram (SNAP)" off
                8 "Elementary Tweaks" off
                9 "Ubuntu Restricted Extras" off
                10 "SM Player Media Player" off
                11 "Gnome Tweak Tool" off
                12 "Google Chrome" off
                13 "Vivaldi" off
                14 "Firefox-Nightly Browser" off
                15 "GIMP" off
                16 "OBS-Studio" off
                17 "Kdenlive" off
                18 "Gnome Boxes" off
                19 "Virtualbox" off
                20 "Atom" off
                21 "Putty" off
                22 "Steam (Valve)" off
                23 "PIA VPN (Network Mgr Version)" off
                24 "Docky" off
                25 "Lutris" off
                26 "Hexchat" off
                27 "Shotwell" off
                28 "Cheese" off
                29 "Audacity" off
                30 "Guvcview (webcam settings)" off
                31 "Pithos (Pandora)" off
                32 "Gnome Shell" off
                33 "Gnome-do (search tool)" off
                34 "Discord (Snap)" off
                35 "Google Desktop Player (rocco)" off
                36 "Etcher" off
                37 "Tilix" off
                38 "Synology NAS Backup" off
                39 "KXStudio Jack Setup (Advanced Audio)" off
                40 "Catfish - File Search" off
                41 "Xfce Monitor Move Script" off
                42 "Thunderbird" off
                43 "Softmaker Office 2016" off
                44 "Oracle Java 10" off
                45 "Cairo-dock" off
                46 "Grub-Customizer" off
                47 "Samba File Systems" off
                48 "Compression Tools" off
                49 "Graphics Misc." off
                50 "Multimedia Misc." off
                51 "HPLIP" off
                52 "Overgrive" off
                53 "Ubuntu Kernel Update Utility" off
                54 "Git" on
                55 "Post Install Auto Clean Up & Update" off
#                56 "Hold for future use" off
#                57 "Hold for future use" off
                )
            choices4=$("${cmd4[@]}" "${options4[@]}" 2>&1 >/dev/tty)
            clear
            case $DISTBASE in
                U)
                    sudo apt update
                	sudo apt install dialog -y

                    for choice4 in $choices4
                    do
                        case $choice4 in
                        
                        1)
                            #Install Sublime Text*
                            echo "Installing Sublime Text"
                            if [ -e /etc/apt/sources.list.d/sublime-text.list ];
                            then
                                sudo apt install sublime-text -y
                            else
                                wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
                                sudo apt install -y apt-transport-https
                                echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
                                sudo apt update
                                sudo apt install sublime-text -y
                            fi
                            ;;

                        2)
                            #Simplenote
                            echo "Installing Simplenote"
                            wget https://github.com/Automattic/simplenote-electron/releases/download/v1.1.7/Simplenote-linux-1.1.7.deb
                            sudo dpkg -i Simplenote-linux-1.1.7.deb
                            sudo rm -rf Simplenote-linux-1.1.7.deb
                            ;;

                        3)	
                            #Install Leafpad
                            echo "Leafpad"
                            sudo apt install leafpad -y
                            ;;
                            
                        4)
                            #Terminology
                            echo "Installing Terminology"
                            sudo apt install terminology -y
                            ;;

                        5)
                            #Filezilla
                            echo "Filezilla not related to Godzilla"
                            sudo apt install filezilla -y
                            ;;
                        6)
                            #Zoom
                            echo "Installing Zoom Meeting Client"
                            echo "Installing dependency first First"				
                            sudo apt install libxcb-xtest0 -y
                            'cd ~/Downloads || return'				
                            wget https://zoom.us/client/latest/zoom_amd64.deb
                            sudo dpkg -i zoom_amd64.deb
                            sudo apt --fix-broken install -y
                            sudo rm -rf zoom_amd64.deb
                            ;;
                        7)
                            #Telegram
                            echo "Telegram Snap"
                            sudo snap install telegram-desktop
                            ;;
                        8)
                            #Elementary OS Tweaks
                            echo "Installing Elementary Tweaks"
                            sudo apt install software-properties-common -y
                            sudo apt update
                            sudo apt install elementary-tweaks -y
                            ;;
                        9)
                            #Ubuntu Restricted Extras
                            echo "Installing Ubuntu Restricted Extras"
                            sudo apt install ubuntu-restricted-extras -y
                            sudo apt --fix-broken install -y
                            ;;
                        10)
                            #SMPlayer
                            echo "SMPlayer"
                            sudo apt install smplayer -y
                            ;;
                        11)
                            #Gnome tweak tool
                            echo "Installing Gnome Tweak Tool"
                            sudo apt install gnome-tweak-tool -y
                            ;;
                        12)

                            #Chrome
                            echo "Installing Google Chrome"
                            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
                            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list'
                            sudo apt update 
                            sudo apt install google-chrome-stable -y
                            ;;
                        13)
                            #Vivaldi
                            echo "Installing Vivaldi"
                            'cd ~/Downloads || return'				
                            wget https://downloads.vivaldi.com/stable/vivaldi-stable_1.15.1147.64-1_amd64.deb
                            sudo dpkg -i vivaldi-stable_1.15.1147.64-1_amd64.deb
                            sudo apt install -f -y
                            rm -rf vivaldi-stable_1.15.1147.64-1_amd64.deb
                            ;;
                        14)

                            #Firefox Browser
                            echo "Firefox-Nightly"
                            if [ -e "/etc/apt/sources.list.d/ubuntu-mozilla-daily-ubuntu-ppa-$(lsb_release -sc).list" ];
                            then
                                sudo apt install firefox-trunk -y
                            else
                                sudo add-apt-repository -yn ppa:ubuntu-mozilla-daily/ppa
                                sudo apt update && sudo apt install firefox-trunk -y
                            fi
                            ;;
                        15)

                            #GIMP
                            echo "Installing GIMP"
                            if [ -e "/etc/apt/sources.list.d/otto-kesselgulasch-ubuntu-gimp-$(lsb_release -sc).list" ];
                            then
                                sudo apt install gimp -y
                            else
                                sudo add-apt-repository -yn ppa:otto-kesselgulasch/gimp
                                sudo apt update && sudo apt install gimp -y
                				sudo apt --fix-broken install -y
                            fi
                            ;;
                        16)
                            #OBS Studio
                            echo "Installing OBS Studio"
                            sudo apt install ffmpeg -y
                            if [ -e "/etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-$(lsb_release -sc).list" ];
                            then
                                if [ "$(lsb_release -sc)" == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/obsproject*; fi
                                sudo apt install obs-studio -y
                            else
                                sudo add-apt-repository ppa:obsproject/obs-studio
                                if [ "$(lsb_release -sc)" == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/obsproject*; fi
                                sudo apt update && sudo apt install obs-studio -y
                            fi
                            ;;
                        17)

                            #Kdenlive
                            echo "Kdenlive"
                            sudo apt install kdenlive -y
                            sudo apt install breeze-icon-theme -y
                            sudo apt install vlc -y
                            ;;
                        18)
                            #Gnome Boxes
                            echo "Installing Gnome Boxes"
                            sudo apt install gnome-boxes -y
                            ;;

                        19)	#Virtualbox
                            echo "Installing Virtualbox"
                            if [ -e /etc/apt/sources.list.d/virtualbox.list ];
                            then
                                sudo apt install -y gcc make linux-headers-"$(uname -r)" dkms
                                sudo apt install virtualbox-5.2 -y
                            else
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo apt-key add -
                                wget -q -O - https://www.virtualbox.org/download/oracle_vbox.asc | sudo apt-key add -
                                sudo sh -c 'echo deb http://download.virtualbox.org/virtualbox/debian "$(lsb_release -sc)" contrib | sudo tee -a /etc/apt/sources.list.d/virtualbox.list'
                                sudo apt -y install gcc make "linux-headers-$(uname -r)" dkms
                                sudo apt install virtualbox-5.2 -y
                            fi
                            ;;

                        20)	#Atom
                            echo "Installing Atom"				
                            'cd ~/Downloads || return'			
                            wget -O atom-amd64.deb https://atom.io/download/deb			
                            sudo dpkg -i atom-amd64.deb
                            sudo apt install -f -y
                            sudo rm -rf atom-amd64.deb
                            sudo apm install atom-html-preview
                            ;;

                        21)	#Putty
                            echo "Putty"
                            sudo apt install putty -y
                            ;;

                        22)	#Steam
                            echo "Installing Steam"				
                            sudo apt install steam -y
                            ;;

                        23)	#PIA VPN
                            echo "Installing PIA VPN Network Manager Version"
                            'cd ~/Downloads || return'				
                            wget https://www.privateinternetaccess.com/installer/install_ubuntu.sh
                            sudo sh ./install_ubuntu.sh
                            echo "After entering username, go to network manager and turn on VPN and select from PIA locations, enter password and boom!"
                            ;;

                        24)	#Docky
                            echo "Installing Docky"
                            sudo apt install docky -y
                            ;;

                        25)	#Lutris
                            echo "Installing Lutris"
                            if [ -e /etc/apt/sources.list.d/lutris.list ];
                            then
                                sudo apt install lutris -y
                            else
                                ver=$(lsb_release -sr); if [ "$ver" != "18.04" ] && [ "$ver" != "17.10" ] && [ "$ver" != "17.04" ] && [ "$ver" != "16.04" ]; then ver="18.04"; fi
                                wget -q http://download.opensuse.org/repositories/home:/strycore/xUbuntu_"$ver"/Release.key -O- | sudo apt-key add -
                                echo "deb http://download.opensuse.org/repositories/home:/strycore/xUbuntu_$ver/ ./" | sudo tee /etc/apt/sources.list.d/lutris.list
                                sudo apt update && sudo apt install lutris -y
                            fi
                            ;;

                        26)	#Hexchat
                            echo "Installing Hexchat"
                            sudo apt install hexchat -y
                            ;;

                        27)	#Shotwell
                            echo "Installing Shotwell"
                            sudo apt install shotwell -y
                            ;;

                        28)	#Cheese
                            echo "Installing Cheese"
                            sudo apt install cheese -y
                            ;;

                        29) 
                            #Audacity
                            echo "installing Audacity"
                            sudo apt install audacity -y
                            ;;

                        30) 
                            #Guvcview
                            echo "installing Guvcview"
                            sudo apt install -y libgslcblas0 guvcview
                            ;;

                        31) 
                            #Pithos
                            echo "installing Pithos"
                            sudo apt install pithos -y
                            ;;
                        
                        32) 
                            #Gnome Shell
                            echo "installing Gnome Shell"
                            sudo apt install chrome-gnome-shell -y
                            ;;
                        
                        33) 
                            #Gnome-do
                            echo "Installing GnomeDo"
                            sudo apt install -y gnome-do gnome-do-plugins
                            ;;
                        34)
                            #Discord
                            sudo snap install discord
                            ;;

                        35) 
                            #Google Desktop Player
                            echo "Installing Google Desktop Player"
                            'cd ~/Downloads || return'
                            wget -O google-play-music-desktop-player.deb https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/releases/download/v4.5.0/google-play-music-desktop-player_4.5.0_amd64.deb
                            sudo dpkg -i google-play-music-desktop-player*.deb
                            sudo apt install -f -y
                            sudo rm -rf google-play-music-desktop-player*.deb
                            ;;

                        36) 
                            #Etcher ISO Creator
                            echo "Installing Etcher"
                            sudo apt install -y etcher-electron
                            ;;

                        37) 
                            #Tilix (Tiling Terminal)
                            echo "Installing Tilix"
                            sudo apt install tilix -y
                            ;;

                        38) 
                            #Synology NAS Assistant & Backup
                            echo "Installing Syn Assist, CloudStation Backup"
                            wget -O synassistant.deb https://global.download.synology.com/download/Tools/Assistant/6.1-15163/Ubuntu/x86_64/synology-assistant_6.1-15163_amd64.deb
                            sudo dpkg -i synassistant*.deb
                            sudo apt install -f -y
                            sudo rm -rf synassistant*.deb
                            wget -O cloudback.deb https://global.download.synology.com/download/Tools/CloudStationBackup/4.2.6-4408/Ubuntu/Installer/x86_64/synology-cloud-station-backup-4408.x86_64.deb
                            sudo dpkg -i cloudback*.deb
                            sudo apt install -f -y
                            sudo rm -rf cloudback*.deb
                            ;;

                        39) 
                            #Advanced Jack Audio Setup
                            echo "installing KXStudio Jack"
                            # Get user name for permissions
                            #echo "Enter your username"
                            #read -r -pr 'Username: ' uservar
                            # Install required dependencies if needed
                            sudo apt install apt-transport-https software-properties-common wget
                            wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.5.1~kxstudio3_all.deb
                            # Install it
                            sudo dpkg -i kxstudio-repos_9.5.1~kxstudio3_all.deb
                            sudo apt install libglibmm-2.4-1v5 -y
                            wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb
                            sudo dpkg -i kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb
                            currentuser=$(who | awk 'NR==1{print $1}')
                                    sudo usermod -a -G audio "$currentuser"
                                    sudo apt update && sudo apt upgrade -y
                                    sudo apt install jackd2-firewire -y
                                    sudo apt install -y jackd2 carla-git cadence non-mixer pulseaudio-module-jack mididings -y
                                    # Download auto script github
                                    'cd ~/ || return'
                                    mkdir jacksetup
                                    'cd ~/jacksetup || return'
                                    wget https://raw.githubusercontent.com/Skrappjaw/audio-scripts/master/start_jack.sh
                                    sudo chmod +x ~/jacksetup/start_jack.sh
                                    sudo chown -R "$currentuser":"$currentuser" ~/jacksetup
                            # Optional to put script into autostart
                            #cd ~/
                            #cp ~/jacksetup/start_jack.sh /etc/init.d/
                            #update-rc.d start_jack.sh defaults
                            ;; 
                        
                        40) 
                            #Install Catfish
                            echo "Installing Catfish"
                            sudo apt install catfish -y
                            ;;

                        41) 
                            #Install monitor move window script Xfce
                            echo "Monitor move window script"
                            wget https://raw.githubusercontent.com/dasgeekchannel/move-to-next-monitor/master/move-to-next-monitor
                            'cd ~/Documents || return'
                            currentuser=$(who | awk 'NR==1{print $1}')
                            sudo chmod +x ~/Documents/move-to-next-monitor
                            sudo chown -R "$currentuser:$currentuser" ~/Documents/move-to-next-monitor
                            ;;

                        42)	
                            #Install Mozilla Thunderbird
                            echo "Installing Thunderbird"
                            if [ -e "/etc/apt/sources.list.d/mozillateam-ubuntu-thunderbird-next-$(lsb_release -sc).list" ];
                            then
                                if [ "$(lsb_release -sc)" == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/mozillateam*; fi
                                sudo apt install thunderbird -y
                            else
                                sudo add-apt-repository -yn ppa:mozillateam/thunderbird-next
                                if [ "$(lsb_release -sc)" == "cosmic" ]; then sudo sed -i 's/cosmic/bionic/g' /etc/apt/sources.list.d/mozillateam*; fi
                                sudo apt update && sudo apt install thunderbird -y
                            fi
                            ;;

                        43)
                            #Install Softmaker Office 2016
                            echo "Installing Softmaker Office 2016"
                            'cd ~/Downloads || return'
                            wget http://www.softmaker.net/down/softmaker-office-2016_761-01_i386.deb
			    #Install Dependencies
                            sudo dpkg --add-architecture i386
                            sudo apt install -y gcc-8-base:i386 libbsd0:i386 libc6:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi6:i386 libgcc1:i386 libgl1:i386
                            sudo apt install -y libgl1-mesa-dri:i386 libgl1-mesa-glx:i386 libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libice6:i386 libidn11:i386 libidn2-0:i386 libllvm6.0:i386 libpciaccess0:i386 libsensors4:i386 libsm6:i386
                            sudo apt install -y libstdc++6:i386 libtinfo6:i386 libunistring2:i386 libuuid1:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386 libxcb-present0:i386 libxcb-sync1:i386 libxcb1:i386
                            sudo apt install -y libxdamage1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxmu6:i386 libxrandr2:i386 libxrender1:i386 libxshmfence1:i386 libxt6:i386 libxxf86vm1:i386 zlib1g:i386
                            sudo dpkg -i softmaker-office-2016_761-01_i386.deb
                            sudo rm ./softmaker-office-2016_761-01_i386.deb
                            ;;

                        44)
                            #Install Oracle Java 10 and set Runtime
                            echo "Installing Oracle Java 10"
                            if [ -e "/etc/apt/sources.list.d/linuxuprising-ubuntu-java-$(lsb_release -sc).list" ];
                            then
                                echo oracle-java10-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
                                sudo apt update && sudo apt install -y oracle-java10-installer
                            else
                                sudo add-apt-repository -yn ppa:linuxuprising/java
                                echo oracle-java10-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
                                sudo apt update && sudo apt install -y oracle-java10-installer
                            fi
                            ;;

                        45)
                            #Install Cairo-dock
                            sudo apt install cairo-dock -y
                            ;;

                        46)
                            #Install Grub-Customizer
                            echo "Installing Grub-Customizer"
                            if [ -e "/etc/apt/sources.list.d/danielrichter2007-ubuntu-grub-customizer-$(lsb_release -sc).list" ];
                            then
                               sudo apt install grub-customizer -y
                            else 
                                sudo add-apt-repository -yn ppa:danielrichter2007/grub-customizer
                                sudo apt update && sudo apt install grub-customizer -y
                            fi
                            ;;

                        47)
                            #Install Samba File Systems
                            echo "Installing File Systems for Samba"
                            sudo apt install -y nfs-common fusesmb samba python-smbc cifs-utils exfat-utils
                            ;;

                        48)
                            #Install Compression Tools
                            echo "Installing Compression Tools"
                            sudo apt install -y engrampa p7zip-rar arj lzip rar unrar rpm2cpio rzip unace
                            ;;

                        49)
                            #Install Misc. Graphics Tools
                            echo "Installing Misc. Graphics Tools"
                            sudo apt install -y darktable gwenview inkscape okular skanlite
                            ;;

                        50)
                            #Install Misc. Multimedia Tools
                            echo "Installing Misc. Multimedia Tools"
                            sudo apt install -y k3b openshot simplescreenrecorder
                            ;;

                        51)
                            #Install HPLIP
                            echo "Installing HPLIP"
                            sudo apt install -y hplip xsane
                            ;;

                        52)
                            #Install  Overgrive
                            echo "Installing Overgrive"
                            sudo add-apt-repository universe && sudo apt update
                            wget https://www.thefanclub.co.za/sites/default/files/public/overgrive/overgrive_3.2.3_all.deb
                            # Steps to fix Overgrive fail to install/start
                                wget https://bootstrap.pypa.io/get-pip.py
                                sudo python2.7 get-pip.py
                                sudo pip2.7 install msgpack-python
                                sudo pip2.7 install --upgrade google-api-python-client
                                sudo pip2.7 install --upgrade oauth2client
                            sudo dpkg -i overgrive_3.2.3_all.deb
                            ;;

                        53)
                            #Ubuntu Kernel Update Utility
                            echo "Installing UKUU"
                            sudo apt install -y ukuu
                            ;;

                        54)
                            #Git
                            echo "Installing Git"
                            sudo apt install -y git
                            ;;

                        55)
                            #Clean up
                            echo "Running Clean Up And Update"
                            sudo apt update
                            sudo apt full-upgrade -y
                            sudo apt autoremove
                            ;;
#
#                        56)
                            #
#                            ;;
#
#                        57)
                            #
#                            ;;
#
                    esac
                done

                    ;;

                A)
                    ;;

                C)
                    ;;

                D)
                    ;;

                F)
                    ;;

                O)
                    ;;
            esac
        for i in "${install_apps[@]}"; do
            app_installer "$i"
        done
    fi

    #Updating Sudoers File to Add NOPASSWD to User
        if [[ "$auto_user_password" != "Y" ]]; then
            sudo rm -f "/etc/sudoers.d/90-$USER"
            sudo -k
        else
            echo "/etc/sudoers.d/90-$USER will remain"
        fi

    #Update hosts file
        echo "I would suggest updating your hosts file for security"
        echo "You might consider using https://someonewhocares.org/hosts/hosts as a base"

	#Reboot Reminder
        echo "Don't forget to reboot before updating to assure proper disk mounting!!!"
